# Generated by Django 4.2.7 on 2023-11-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('seat_id', models.CharField(max_length=10)),
                ('occupancy', models.BooleanField()),
            ],
        ),
    ]
